// Code generated by protoc-gen-go. DO NOT EDIT.
// source: click.proto

package connection

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Click struct {
	TdsId                uint32   `protobuf:"varint,1,opt,name=TdsId,proto3" json:"TdsId,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Ip                   uint32   `protobuf:"varint,3,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Query                []byte   `protobuf:"bytes,4,opt,name=Query,proto3" json:"Query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Click) Reset()         { *m = Click{} }
func (m *Click) String() string { return proto.CompactTextString(m) }
func (*Click) ProtoMessage()    {}
func (*Click) Descriptor() ([]byte, []int) {
	return fileDescriptor_764ede89b454d19e, []int{0}
}

func (m *Click) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Click.Unmarshal(m, b)
}
func (m *Click) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Click.Marshal(b, m, deterministic)
}
func (m *Click) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Click.Merge(m, src)
}
func (m *Click) XXX_Size() int {
	return xxx_messageInfo_Click.Size(m)
}
func (m *Click) XXX_DiscardUnknown() {
	xxx_messageInfo_Click.DiscardUnknown(m)
}

var xxx_messageInfo_Click proto.InternalMessageInfo

func (m *Click) GetTdsId() uint32 {
	if m != nil {
		return m.TdsId
	}
	return 0
}

func (m *Click) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Click) GetIp() uint32 {
	if m != nil {
		return m.Ip
	}
	return 0
}

func (m *Click) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func init() {
	proto.RegisterType((*Click)(nil), "connection.Click")
}

func init() { proto.RegisterFile("click.proto", fileDescriptor_764ede89b454d19e) }

var fileDescriptor_764ede89b454d19e = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0xc9, 0x4c,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xce, 0xcf, 0xcb, 0x4b, 0x4d, 0x2e,
	0xc9, 0xcc, 0xcf, 0x53, 0x0a, 0xe6, 0x62, 0x75, 0x06, 0x49, 0x09, 0x89, 0x70, 0xb1, 0x86, 0xa4,
	0x14, 0x7b, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x41, 0x38, 0x42, 0x7c, 0x5c, 0x4c,
	0x9e, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x4c, 0x50, 0x7e, 0x81, 0x04, 0x33, 0x58,
	0x09, 0x93, 0x67, 0x01, 0x48, 0x57, 0x60, 0x69, 0x6a, 0x51, 0xa5, 0x04, 0x8b, 0x02, 0xa3, 0x06,
	0x4f, 0x10, 0x84, 0xe3, 0x24, 0x18, 0xc5, 0x9f, 0x1e, 0x14, 0xe0, 0xac, 0x8f, 0xb0, 0x27, 0x89,
	0x0d, 0x6c, 0xb5, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xab, 0x55, 0xd9, 0x1d, 0x89, 0x00, 0x00,
	0x00,
}
