// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connection-service.proto

package connection

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Connection struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{0}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Connection) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Connection) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type ClickResponse struct {
	Click                *Click      `protobuf:"bytes,1,opt,name=click,proto3" json:"click,omitempty"`
	Connection           *Connection `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	Error                *Error      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClickResponse) Reset()         { *m = ClickResponse{} }
func (m *ClickResponse) String() string { return proto.CompactTextString(m) }
func (*ClickResponse) ProtoMessage()    {}
func (*ClickResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{1}
}

func (m *ClickResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClickResponse.Unmarshal(m, b)
}
func (m *ClickResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClickResponse.Marshal(b, m, deterministic)
}
func (m *ClickResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClickResponse.Merge(m, src)
}
func (m *ClickResponse) XXX_Size() int {
	return xxx_messageInfo_ClickResponse.Size(m)
}
func (m *ClickResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClickResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClickResponse proto.InternalMessageInfo

func (m *ClickResponse) GetClick() *Click {
	if m != nil {
		return m.Click
	}
	return nil
}

func (m *ClickResponse) GetConnection() *Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

func (m *ClickResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ClickData struct {
	Id                   int64       `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Click                *Click      `protobuf:"bytes,2,opt,name=click,proto3" json:"click,omitempty"`
	Connection           *Connection `protobuf:"bytes,3,opt,name=connection,proto3" json:"connection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClickData) Reset()         { *m = ClickData{} }
func (m *ClickData) String() string { return proto.CompactTextString(m) }
func (*ClickData) ProtoMessage()    {}
func (*ClickData) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{2}
}

func (m *ClickData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClickData.Unmarshal(m, b)
}
func (m *ClickData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClickData.Marshal(b, m, deterministic)
}
func (m *ClickData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClickData.Merge(m, src)
}
func (m *ClickData) XXX_Size() int {
	return xxx_messageInfo_ClickData.Size(m)
}
func (m *ClickData) XXX_DiscardUnknown() {
	xxx_messageInfo_ClickData.DiscardUnknown(m)
}

var xxx_messageInfo_ClickData proto.InternalMessageInfo

func (m *ClickData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ClickData) GetClick() *Click {
	if m != nil {
		return m.Click
	}
	return nil
}

func (m *ClickData) GetConnection() *Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Connection)(nil), "connection.Connection")
	proto.RegisterType((*ClickResponse)(nil), "connection.ClickResponse")
	proto.RegisterType((*ClickData)(nil), "connection.ClickData")
	proto.RegisterType((*Error)(nil), "connection.Error")
}

func init() { proto.RegisterFile("connection-service.proto", fileDescriptor_80f86ad761877d5c) }

var fileDescriptor_80f86ad761877d5c = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x84, 0x82, 0x72, 0x11, 0xa0, 0x58, 0x02, 0x99, 0x4e, 0x55, 0x16, 0xba, 0x10,
	0xa4, 0x20, 0xd8, 0x58, 0x68, 0x19, 0xba, 0xba, 0x1b, 0x5b, 0x70, 0x4e, 0x25, 0x02, 0xec, 0xc8,
	0xb6, 0x98, 0xf8, 0x23, 0xfc, 0x5b, 0xe4, 0x73, 0x49, 0x0a, 0x59, 0xe8, 0xf6, 0xe2, 0xf7, 0x74,
	0xef, 0x3b, 0x3b, 0xc0, 0xa5, 0x56, 0x0a, 0xa5, 0x6b, 0xb5, 0xba, 0xb2, 0x68, 0x3e, 0x5a, 0x89,
	0x65, 0x67, 0xb4, 0xd3, 0x0c, 0x06, 0x67, 0x9a, 0xc9, 0xb7, 0x56, 0xbe, 0x06, 0xa3, 0x58, 0x02,
	0x2c, 0x7a, 0x8b, 0x9d, 0x40, 0xbc, 0x6a, 0x78, 0x34, 0x8b, 0xe6, 0x89, 0x88, 0x57, 0x0d, 0x63,
	0x70, 0xf0, 0xa2, 0xad, 0xe3, 0xf1, 0x2c, 0x9a, 0xa7, 0x82, 0xb4, 0x3f, 0xeb, 0xb4, 0x71, 0x3c,
	0x09, 0x67, 0x5e, 0x17, 0x5f, 0x11, 0x1c, 0x2f, 0xfc, 0x54, 0x81, 0xb6, 0xd3, 0xca, 0x22, 0xbb,
	0x84, 0x09, 0xd5, 0xd0, 0xb0, 0xac, 0xca, 0xcb, 0x01, 0xa0, 0x0c, 0xc9, 0xe0, 0xb3, 0x3b, 0xd8,
	0x61, 0xa3, 0xa2, 0xac, 0x3a, 0xff, 0x95, 0xee, 0xa5, 0xd8, 0x49, 0xfa, 0x02, 0x34, 0x46, 0x1b,
	0xe2, 0xf8, 0x53, 0xf0, 0xe8, 0x0d, 0x11, 0xfc, 0xe2, 0x13, 0x52, 0x2a, 0x5c, 0xd6, 0xae, 0x1e,
	0x2d, 0xd8, 0x63, 0xc6, 0x7b, 0x61, 0x26, 0xff, 0xc5, 0x2c, 0x6e, 0x61, 0x42, 0x34, 0xfe, 0xda,
	0xa4, 0x6e, 0x90, 0xba, 0x53, 0x41, 0x9a, 0x71, 0x38, 0x7a, 0x47, 0x6b, 0xeb, 0x0d, 0x6e, 0x6f,
	0xf8, 0xe7, 0xb3, 0x12, 0x90, 0x0f, 0x03, 0xd7, 0xe1, 0x29, 0xd9, 0x3d, 0xa4, 0x6b, 0x54, 0x0d,
	0x71, 0xb1, 0xb3, 0x11, 0xaa, 0x5f, 0x70, 0x7a, 0x31, 0xde, 0x60, 0xfb, 0x24, 0x0f, 0xf9, 0xd3,
	0xe9, 0xc6, 0x74, 0xf2, 0x7a, 0x08, 0x3c, 0x1f, 0xd2, 0x4f, 0x70, 0xf3, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x99, 0x88, 0x70, 0x2f, 0x39, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectionServiceClient interface {
	SendClick(ctx context.Context, in *ClickData, opts ...grpc.CallOption) (*ClickResponse, error)
}

type connectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewConnectionServiceClient(cc *grpc.ClientConn) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) SendClick(ctx context.Context, in *ClickData, opts ...grpc.CallOption) (*ClickResponse, error) {
	out := new(ClickResponse)
	err := c.cc.Invoke(ctx, "/connection.ConnectionService/SendClick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
type ConnectionServiceServer interface {
	SendClick(context.Context, *ClickData) (*ClickResponse, error)
}

// UnimplementedConnectionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConnectionServiceServer struct {
}

func (*UnimplementedConnectionServiceServer) SendClick(ctx context.Context, req *ClickData) (*ClickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendClick not implemented")
}

func RegisterConnectionServiceServer(s *grpc.Server, srv ConnectionServiceServer) {
	s.RegisterService(&_ConnectionService_serviceDesc, srv)
}

func _ConnectionService_SendClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).SendClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connection.ConnectionService/SendClick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).SendClick(ctx, req.(*ClickData))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connection.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendClick",
			Handler:    _ConnectionService_SendClick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection-service.proto",
}
